# -*- coding: utf-8 -*-
"""Лабораторная 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HtsWMVQSEOeMsCiFtkn8wQxNe6fK6JYe

Задание 1
"""

n=int(input())
if n == 1:
  print("январь")
elif n == 2:
  print("февраль")
elif n == 3:
  print("март")
elif n == 4:
  print("апрель")
elif n == 5:
  print("май")
elif n == 6:
  print("июнь")
elif n == 7:
  print("июль")
elif n == 8:
  print("август")
elif n == 9:
  print("сентябрь")
elif n == 10:
  print("октябрь")
elif n == 11:
  print("ноябрь")
elif n == 12:
  print("декабрь")
else:
  print("ошибка")

"""Задание 2"""

n = int(input())
if n%2 == 0:
  print("четное")
else:
  print("нечетное")

"""Задание 3"""

n = int(input())
if n>=40:
  print("stonks")
else:
  print("not stonks")

"""Задание 4"""

is_year_leap=int(input())
if is_year_leap%4==0:
  print("True")
else:
  print("False")

"""Задание 5"""

n=int(input())

is_prime=True
i=2
while i<n:
  if n%i==0:
    is_prime=False
  i=i+1

if is_prime==True:
  print("True")
else:
  print("False")

"""Задание 6"""

a=float(input())
b=float(input())
c=abs((-138/2)**1.3)
d=abs((-69/28**5.1)*4)
if a/b==3.6:
  a,b = b,a
  print(a,b)
elif c<=b and b<=d:
  a,b = b,a
  print(a,b)
else:
  print(a,b)

"""Задание 7"""

a=int(input())
b=int(input())
c=int(input())
d=int(input())
e=int(input())

if a == b:
  print("Не уникальны")
elif a==c:
  print("Не уникальны")
elif a==d:
  print("Не уникальны")
elif a==e:
  print("Не уникальны")

elif b==c:
  print("Не уникальны")
elif b==d:
  print("Не уникальны")
elif b==e:
  print("Не уникальны")

elif c==d:
  print("Не уникальны")
elif c==e:
  print("Не уникальны")

elif d==e:
  print("Не уникальны")

else:
  print("уникальны")

k=0
if a%2==0:
  k=k+1
if b%2==0:
  k=k+1
if c%2==0:
  k=k+1
if d%2==0:
  k=k+1
if e%2==0:
  k=k+1
print(f"Четных чисел - {k}")

i = 0
4
if a<0:
  i=i+1
if b<0:
  i=i+1
if c<0:
  i=i+1
if d<0:
  i=i+1
if e<0:
  i=i+1
print(f"отрицательных чисел - {i}")

n=-256
m=1024
f=0

if a>n and a<m:
  f=f+1
if b>n and b<m:
  f=f+1
if c>n and c<m:
  f=f+1
if d>n and d<m:
  f=f+1
if e>n and e<m:
  f=f+1
print(f"попали в промежуток - {f}")

"""Задание сложное"""

a=int(input())
b=int(input())
c=int(input())
d=(a**2+b**3)/(c+3)/4

if d%2==0:
  print(f"{d} is even")
else:
  print(f"{d} is not even")